using AdventOfCode.Solutions.Year2025;

namespace AdventOfCode.Tests.Year2025;

public class Day07Tests : IClassFixture<Day07>
{
    private readonly Day07 _sut;

    private const string TestData = """
                                    .......S.......
                                    ...............
                                    .......^.......
                                    ...............
                                    ......^.^......
                                    ...............
                                    .....^.^.^.....
                                    ...............
                                    ....^.^...^....
                                    ...............
                                    ...^.^...^.^...
                                    ...............
                                    ..^...^.....^..
                                    ...............
                                    .^.^.^.^.^...^.
                                    ...............
                                    """;

    public Day07Tests(Day07 sut)
    {
        _sut = sut;
    }

    [Fact]
    public void Part1Test()
    {
        _sut.Part1(TestData).As<int>().Should().Be(21);
    }

    [Fact]
    public void Part2Test()
    {
        _sut.Part2(TestData).As<long>().Should().Be(40);
    }
}